volumes:
  filesdata:
  pgdata:
name: Luna

services:
  database:
    container_name: database
    image: postgres:18
    restart: on-failure:3
    expose:
      - "5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: luna
    volumes:
      - pgdata:/var/lib/postgresql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    container_name: backend
    restart: on-failure:3
    build:
      dockerfile: docker/backend.Dockerfile
      context: .
    ports:
      - "3000:3000"
    depends_on:
      database:
        condition: service_healthy
    volumes:
      - filesdata:/app/files

  bot:
    container_name: bot
    restart: on-failure # ⚠️ watch this
    build:
      dockerfile: docker/bot.Dockerfile
      context: .
    depends_on:
      database:
        condition: service_healthy
    volumes:
      - filesdata:/app/files
