name: Luna
volumes:
  dragonflydata:

services:

  dragonfly:
    container_name: dragonfly
    image: ghcr.io/dragonflydb/dragonfly:v1.37.2
    restart: on-failure:3
    expose:
      - "6379"
    volumes:
      - dragonflydata:/data

  backend:
    container_name: backend
    restart: on-failure:3
    build:
      dockerfile: docker/backend.Dockerfile
      context: .
    ports:
      - "3000:3000"
    depends_on:
      init-db:
        condition: service_completed_successfully
      # database:
      #   condition: service_healthy
      dragonfly:
        condition: service_healthy
    volumes:
      - ./files:/app/files

  bot:
    container_name: bot
    restart: on-failure:3
    build:
      dockerfile: docker/bot.Dockerfile
      context: .
    depends_on:
      init-db:
        condition: service_completed_successfully
      # database:
      #   condition: service_healthy
      dragonfly:
        condition: service_healthy
    volumes:
      - ./files:/app/files
      - ./assets:/app/assets
  init-db:
    container_name: init-db
    build:
      dockerfile: docker/init-db.Dockerfile
      context: .
    restart: no